// 3. Faça um Programa que pergunte ao usuário o seu nome e, em
// seguida, mostre o nome do usuário na tela.


package prog_exercicios;

import java.util.Scanner;


public class exercicio3 {
	
	public static void main(String[] args) {
		
		Scanner input = new Scanner(System.in);
		System.out.print("Digite o seu nome: ");
		
		String nome = input.nextLine();
		
		System.out.println("Seu nome é: " + nome);
		
		
		
		
		
		
	}
	

}
